export default {
  name: 'Ingrediënten',
  children: [
    {
      name: 'polymers',
      functions: [
        'give strength',
        ' adhesion',
        ' coating',
        ' binder',
        ' growth substrate',
        ' enforcement or scaffold in composites',
      ],
      children: [
        {
          name: 'polysaccharides',
          children: [
            {
              name: 'cellulose',
              base: 'plants',
              origin: [
                ' cotton',
                ' linen',
                ' hemp',
                ' jute',
                ' flax',
                ' ramie',
                ' pineapple',
                ' kenaf',
                ' abaca',
                ' henequen',
                ' wood',
                ' most plants',
              ],
              link: 'https://nl.wikipedia.org/wiki/Cellulose',
              category: 'polymers',
              subcategory: 'polysaccharides',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 3938,
            },
            {
              name: 'pectin',
              base: 'plants',
              origin: [
                '(peels of) apples',
                ' apricots',
                ' cherries',
                ' passion fruit',
                ' carrot',
                ' citrus fruit',
                ' rose hips',
                ' guava',
                ' quince',
                ' plums',
                ' gooseberries',
                ' strawberries',
                ' bananas',
                ' grapes',
              ],
              link: 'https://en.wikipedia.org/wiki/Pectin',
              category: 'polymers',
              subcategory: 'polysaccharides',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 3812,
            },
            {
              name: 'hemi-cellulose',
              base: 'plants',
              origin: ['green beans', ' rice straws'],
              link: 'https://nl.wikipedia.org/wiki/Hemicellulose',
              category: 'polymers',
              subcategory: 'polysaccharides',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 6714,
            },
            {
              name: 'starches',
              base: 'plants',
              origin: [
                'corn',
                ' wheat',
                ' rice',
                ' tapioca',
                ' potato',
                ' cassava',
              ],
              link: 'https://en.wikipedia.org/wiki/Starch',
              category: 'polymers',
              subcategory: 'polysaccharides',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 743,
            },
            {
              name: 'lignin',
              base: 'plants',
              origin: [
                'wood',
                ' bark',
                ' plant stems',
                ' potato tubers',
                ' rice straws',
                ' jute',
                ' hemp',
                ' cotton',
                ' wheat straw',
                ' pine straw',
                ' flax fibre',
                ' alfalfa',
              ],
              link: 'https://en.wikipedia.org/wiki/Lignin',
              category: 'polymers',
              subcategory: 'polysaccharides',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 743,
            },
            {
              name: 'gums',
              base: 'plants',
              origin: ['gum arabic', ' tara gum', ' guar gum'],
              link: 'https://en.wikipedia.org/wiki/Gums',
              category: 'polymers',
              subcategory: 'polysaccharides',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 743,
            },
            {
              name: 'cellulose',
              base: 'microbial',
              origin: ['acetobacter xylinum (kombucha)', ' mycelium'],
              link: 'https://nl.wikipedia.org/wiki/Cellulose',
              category: 'polymers',
              subcategory: 'polysaccharides',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 743,
            },
            {
              name: 'gums (bacteria)',
              base: 'microbial',
              origin: [
                'xanthan',
                ' gellan',
                ' bacterial alginate (azotobacter vinelandii',
              ],
              link: 'https://en.wikipedia.org/wiki/Gums',
              category: 'polymers',
              subcategory: 'polysaccharides',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 743,
            },
            {
              name: 'gums (algea)',
              base: 'microbial',
              origin: ['alginate', ' agar', ' carrageenan'],
              link: 'https://en.wikipedia.org/wiki/Gums',
              category: 'polymers',
              subcategory: 'polysaccharides',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 743,
            },
            {
              name: 'fermented biomass',
              base: 'microbial',
              origin: ['PLA (corn)'],
              link: 'empty',
              category: 'polymers',
              subcategory: 'polysaccharides',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 743,
            },
            {
              name: 'chemically modified cellulose',
              base: 'chemical compounds',
              origin: [
                'Carboxy Methyl Cellulose (CMC)',
                ' Methyl Cellulose (MC)',
              ],
              link: 'https://nl.wikipedia.org/wiki/Cellulose',
              category: 'polymers',
              subcategory: 'polysaccharides',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 743,
            },
          ],
        },
        {
          name: 'protein',
          children: [
            {
              name: 'albumin',
              base: 'animal',
              origin: ['blood', ' beef', ' eggs'],
              link: 'https://nl.wikipedia.org/wiki/Prote%C3%AFne',
              category: 'polymers',
              subcategory: 'protein',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 3534,
            },
            {
              name: 'silk',
              base: 'animal',
              origin: ['silk', ' spider silk'],
              link: 'https://en.wikipedia.org/wiki/Silk',
              category: 'polymers',
              subcategory: 'protein',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 5731,
            },
            {
              name: 'keratin',
              base: 'animal',
              origin: ['wool', ' hair', ' nails', ' feathers', ' fur'],
              link: 'https://en.wikipedia.org/wiki/Keratin',
              category: 'polymers',
              subcategory: 'protein',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 7840,
            },
            {
              name: 'fibrin',
              base: 'animal',
              origin: ['protein found in blood'],
              link: 'https://en.wikipedia.org/wiki/Fibrin',
              category: 'polymers',
              subcategory: 'protein',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 5914,
            },
            {
              name: 'chitin (animal)',
              base: 'animal',
              origin: ['exoskeletons of crustaceans', ' crabs', ' shrimps'],
              link: 'https://en.wikipedia.org/wiki/Chitin',
              category: 'polymers',
              subcategory: 'protein',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 3416,
            },
            {
              name: 'collagen',
              base: 'animal',
              origin: [
                'gelatin',
                ' skin, bones and connective tissue of e.g.chicken, pig, fish, cow',
              ],
              link: 'https://nl.wikipedia.org/wiki/Collageen',
              category: 'polymers',
              subcategory: 'protein',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 3416,
            },
            {
              name: 'casein',
              base: 'animal',
              origin: ['milk'],
              link: 'https://en.wikipedia.org/wiki/Casein',
              category: 'polymers',
              subcategory: 'protein',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 3416,
            },
            {
              name: 'gluten',
              base: 'plants',
              origin: [
                'wheat',
                ' barley',
                ' rye',
                ' oats',
                ' spelt',
                ' khorasan',
                ' emmer',
                ' einkorn',
                ' triticale',
              ],
              link: 'https://nl.wikipedia.org/wiki/Gluten',
              category: 'polymers',
              subcategory: 'protein',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 3416,
            },
            {
              name: 'zein',
              base: 'plants',
              origin: ['corn'],
              link: 'https://en.wikipedia.org/wiki/Zein',
              category: 'polymers',
              subcategory: 'protein',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 3416,
            },
            {
              name: 'soy',
              base: 'plants',
              origin: ['soy beans'],
              link: 'https://en.wikipedia.org/wiki/Soybean',
              category: 'polymers',
              subcategory: 'protein',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 3416,
            },
            {
              name: 'chitin (fungal)',
              base: 'plants',
              origin: ['fungal mycelium'],
              link: 'https://nl.wikipedia.org/wiki/Chitine',
              category: 'polymers',
              subcategory: 'protein',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 3416,
            },
          ],
        },
        {
          name: 'resins',
          children: [
            {
              name: 'resin (animal)',
              base: 'animal',
              origin: ['shellac'],
              link: 'https://en.wikipedia.org/wiki/Resin',
              category: 'polymers',
              subcategory: 'resins',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 7074,
            },
            {
              name: 'resin (plant)',
              base: 'plants',
              origin: [
                'copal',
                ' kauri gum',
                ' turpentine',
                ' spinifex',
                ' sandarac',
                ' cabdanum',
                ' mastic',
                ' urushi',
                ' arabic gum',
              ],
              link: 'https://en.wikipedia.org/wiki/Resin',
              category: 'polymers',
              subcategory: 'resins',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 3416,
            },
          ],
        },
        {
          name: 'elastomers & rubbers',
          children: [
            {
              name: 'elastomer (plant)',
              base: 'plants',
              link: 'https://en.wikipedia.org/wiki/Elastomer',
              category: 'polymers',
              subcategory: 'elastomers & rubbers',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 7074,
            },
            {
              name: 'elastomer (synthetic)',
              base: 'petrol-based',
              origin: ['synthetic latex'],
              link: 'https://en.wikipedia.org/wiki/Elastomer',
              category: 'polymers',
              subcategory: 'elastomers & rubbers',
              categoryFunctions: [
                'give strength',
                ' adhesion',
                ' coating',
                ' binder',
                ' growth substrate',
                ' enforcement or scaffold in composites',
              ],
              size: 3416,
            },
          ],
        },
      ],
    },
    {
      name: 'plasticizers',
      functions: [
        'give flexibility to biopolymer recipes',
        ' acts as a partial filler as well (in bioplastics, inks and paints)',
      ],
      children: [
        {
          name: 'poylols',
          base: 'animal',
          origin: ['animal glycerine (cow, sheep)'],
          link: 'empty',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 1983,
        },
        {
          name: 'urea',
          base: 'animal',
          origin: ['urine'],
          link: 'https://en.wikipedia.org/wiki/Urea',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 2047,
        },
        {
          name: 'waxes',
          base: 'animal',
          origin: ['bees wax'],
          link: 'https://en.wikipedia.org/wiki/Wax',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 1375,
        },
        {
          name: 'other',
          base: 'animal',
          origin: ['honey'],
          link: 'empty',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 8746,
        },
        {
          name: 'poylols',
          base: 'plants',
          origin: ['vegetable glycerine (soy, palm, coconut)'],
          link: 'empty',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 2202,
        },
        {
          name: 'lecithin',
          base: 'plants',
          origin: ['soy'],
          link: 'https://en.wikipedia.org/wiki/Lecithin',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 1382,
        },
        {
          name: 'waxes',
          base: 'plants',
          origin: ['candellila', ' carnauba'],
          link: 'https://en.wikipedia.org/wiki/Wax',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 1629,
        },
        {
          name: 'monosaccharides',
          base: 'plants',
          origin: ['glucose', ' mannose', ' fructose', ' sucrose'],
          link: 'https://en.wikipedia.org/wiki/Monosaccharide',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 1675,
        },
        {
          name: 'vegetable oils',
          base: 'plants',
          origin: ['sunflower oil', ' rice oil'],
          link: 'https://en.wikipedia.org/wiki/Vegetable_oil',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 2042,
        },
        {
          name: 'poylols',
          base: 'microbial',
          origin: ['microbial glycerine (yeast , algae)', ' sugar alcohols'],
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          link: 'empty',
          size: 2042,
        },
        {
          name: 'water',
          base: 'inorganic',
          origin: ['water'],
          link: 'https://en.wikipedia.org/wiki/Water',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 2042,
        },
        {
          name: 'poylols',
          base: 'chemical compounds',
          origin: [
            'sorbitol',
            ' mannitol',
            ' xylitol',
            ' ethylene- diethylene- triethylene, - tetraethylene and polyethylene glycol',
            ' propylene glycol',
          ],
          link: 'empty',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 2042,
        },
        {
          name: 'surfactants',
          base: 'chemical compounds',
          origin: ['soap', ' glycerol monostrearate'],
          link: 'https://en.wikipedia.org/wiki/Surfactant#:~:text=Surfactants%20are%20compounds%20that%20lower,%2C%20foaming%20agents%2C%20or%20dispersants.',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 2042,
        },
        {
          name: 'poylols',
          base: 'petrol-based',
          origin: ['petroleum-based glycerine'],
          link: 'empty',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 2042,
        },
        {
          name: 'waxes & paraffines',
          base: 'petrol-based',
          origin: ['paraffine (petrol)'],
          link: 'https://en.wikipedia.org/wiki/Paraffin_wax',
          category: 'plasticizers',
          categoryFunctions: [
            'give flexibility to biopolymer recipes',
            ' acts as a partial filler as well (in bioplastics, inks and paints)',
          ],
          size: 2042,
        },
      ],
    },
    {
      name: 'pigments',
      functions: [
        'give color: note that everything that has pigment acts well as a dye',
      ],
      children: [
        {
          name: 'animal',
          base: 'animal',
          origin: [
            'cochineal and lac insects',
            ' octopus ink (sepia)',
            ' murex snail',
            ' blood',
            ' bone black',
            ' egg shells',
          ],
          link: 'https://en.wikipedia.org/wiki/Animal',
          category: 'pigments',
          categoryFunctions: [
            'give color: note that everything that has pigment acts well as a dye',
          ],
          size: 1759,
        },
        {
          name: 'tree (leaves, bark, seeds or fruits)',
          base: 'plants',
          origin: [
            'campeche',
            ' brazilwood',
            ' old fustic',
            ' sandalwood',
            ' birch',
            ' chestnut',
            ' acacia (cutch)',
            ' bixa orellana (annatto)',
            ' terminalia chebula (myrobalan nuts)',
            ' oak bark',
            ' pine (branches)',
            ' quebracho',
            ' walnut (leaves)',
            ' buckthorn (bark)',
          ],
          link: 'https://en.wikipedia.org/wiki/Plant',
          category: 'pigments',
          categoryFunctions: [
            'give color: note that everything that has pigment acts well as a dye',
          ],
          size: 2165,
        },
        {
          name: 'plant',
          base: 'plants',
          origin: [
            'alkanet',
            ' turmeric root',
            ' onion skin',
            ' madder',
            ' oak/wasp cherry galls',
            ' avocado stones and skin',
            ' grape black',
            ' sap green',
            ' black beans',
            ' henna',
            ' mahonia aquifolia (branches)',
            ' marigold',
            ' pomegranate (rind)',
            ' indigo tinctoria',
            ' woad',
            ' weld',
            ' goldenrod',
            ' rhubarb (roots)',
            " saint john's wort",
            ' chamomile',
            ' coreopsis',
            ' saw wort',
            ' eucalyptus',
            ' safflower',
            ' greenweed',
          ],
          link: 'https://en.wikipedia.org/wiki/Plant',
          category: 'pigments',
          categoryFunctions: [
            'give color: note that everything that has pigment acts well as a dye',
          ],
          size: 586,
        },
        {
          name: 'fungi',
          base: 'plants',
          origin: [
            'phaeolus schweinitzii',
            ' hypholoma fasciculare',
            ' scleroderma aerolatum',
            ' cortinarius (semi)sanguineus',
            ' hapalopilus rutilans',
            ' paxillus involutus',
            ' inonotus hispidus',
            ' hydnellum geogenium',
            ' sarcodon squamosus',
            ' polyozellus multiplex',
            ' clavariadelphus occidentalis',
            ' gyromitra infula',
            ' anthracophyllum lateritium',
            ' cortinarius marylandensis',
          ],
          link: 'https://en.wikipedia.org/wiki/Fungus',
          category: 'pigments',
          categoryFunctions: [
            'give color: note that everything that has pigment acts well as a dye',
          ],
          size: 3331,
        },
        {
          name: 'micro-algae',
          base: 'microbial',
          origin: [
            'chlorella',
            ' arthrospiria platensis (spirulina)',
            ' bioluminescent dinaflagellates',
            ' haematococcus pluvialis',
            ' porphyridium purpureum',
            ' dunaliella salina',
          ],
          link: 'https://en.wikipedia.org/wiki/Microalgae',
          category: 'pigments',
          categoryFunctions: [
            'give color: note that everything that has pigment acts well as a dye',
          ],
          size: 772,
        },
        {
          name: 'bacteria',
          base: 'microbial',
          origin: [
            'serratia marcescens',
            ' rhodococcus rhodochrous',
            ' janthinobacterium lividum',
            ' vogesella indigofera',
            ' micrococcus luteus',
            ' sarcina aurantiaca',
            ' arthrobacter agilis',
            ' streptomyces coelicolor',
            ' kluyveromyces marxianus',
            ' burkholderia cepacia',
            ' monascus roseus',
            ' pacilmyces farinosus',
            ' allochromatum vinosum',
          ],
          link: 'https://en.wikipedia.org/wiki/Bacteria',
          category: 'pigments',
          categoryFunctions: [
            'give color: note that everything that has pigment acts well as a dye',
          ],
          size: 3322,
        },
        {
          name: 'fungi & yeast',
          base: 'microbial',
          origin: ['monascus purpureus', ' chlorociboria aeruginascens'],
          link: 'empty',
          category: 'pigments',
          categoryFunctions: [
            'give color: note that everything that has pigment acts well as a dye',
          ],
          size: 772,
        },
        {
          name: 'clays & earth',
          base: 'inorganic',
          origin: ['ochre', ' sienna', ' umber', ' green earth'],
          link: 'empty',
          category: 'pigments',
          categoryFunctions: [
            'give color: note that everything that has pigment acts well as a dye',
          ],
          size: 772,
        },
        {
          name: 'rocks',
          base: 'inorganic',
          origin: ['lapis lazuli'],
          link: 'empty',
          size: 772,
          category: 'pigments',
          categoryFunctions: [
            'give color: note that everything that has pigment acts well as a dye',
          ],
        },
        {
          name: 'minerals',
          base: 'inorganic',
          origin: ['vicenza earth', ' azurite', ' turkoise'],
          link: 'https://en.wikipedia.org/wiki/Mineral',
          category: 'pigments',
          categoryFunctions: [
            'give color: note that everything that has pigment acts well as a dye',
          ],
          size: 772,
        },
      ],
    },
    {
      name: 'pH modifiers',
      functions: ['change the pH of a liquid'],
      children: [
        {
          name: 'acidic',
          base: 'plants',
          origin: ['hibiscus flowers', ' fruit (lemon) juice'],
          link: 'https://en.wikipedia.org/wiki/Acid',
          category: 'pH modifiers',
          categoryFunctions: ['change the pH of a liquid'],
          size: 1759,
        },
        {
          name: 'acidic',
          base: 'microbial',
          origin: ['vinegar'],
          link: 'https://en.wikipedia.org/wiki/Acid',
          category: 'pH modifiers',
          categoryFunctions: ['change the pH of a liquid'],
          size: 2165,
        },
        {
          name: 'alkaline',
          base: 'inorganic',
          origin: ['chalk', ' slaked lime'],
          link: 'https://en.wikipedia.org/wiki/Alkali',
          category: 'pH modifiers',
          categoryFunctions: ['change the pH of a liquid'],
          size: 586,
        },
        {
          name: 'acidic',
          base: 'inorganic',
          origin: ['alum'],
          link: 'https://en.wikipedia.org/wiki/Acid',
          category: 'pH modifiers',
          categoryFunctions: ['change the pH of a liquid'],
          size: 3331,
        },
        {
          name: 'alkaline',
          base: 'chemical compounds',
          origin: [
            'sodium carbonate',
            ' sodium bicarbonate',
            ' calcium carbonate',
            ' ammonia',
          ],
          link: 'https://en.wikipedia.org/wiki/Alkali',
          category: 'pH modifiers',
          categoryFunctions: ['change the pH of a liquid'],
          size: 772,
        },
        {
          name: 'acidic',
          base: 'chemical compounds',
          origin: ['citric acid', ' cream of tartar', ' alum'],
          category: 'pH modifiers',
          categoryFunctions: ['change the pH of a liquid'],
          link: 'https://en.wikipedia.org/wiki/Acid',
          size: 3322,
        },
      ],
    },
    {
      name: 'surfactants',
      functions: [
        'change surface tension between liquids',
        ' emulsifying, foaming',
      ],
      children: [
        {
          name: 'detergents',
          base: 'chemical compounds',
          origin: ['hand soap', ' dishwashing soap'],
          link: 'https://en.wikipedia.org/wiki/Detergent',
          category: 'surfactants',
          categoryFunctions: [
            'change surface tension between liquids',
            ' emulsifying, foaming',
          ],
          size: 1759,
        },
        {
          name: 'alcohols',
          base: 'chemical compounds',
          origin: ['methylated spirit'],
          link: 'https://en.wikipedia.org/wiki/Alcohol_(chemistry)',
          category: 'surfactants',
          categoryFunctions: [
            'change surface tension between liquids',
            ' emulsifying, foaming',
          ],
          size: 2165,
        },
        {
          name: 'monoglycerides',
          base: 'chemical compounds',
          origin: ['glycerol monostearate'],
          link: 'https://en.wikipedia.org/wiki/Monoglyceride',
          category: 'surfactants',
          categoryFunctions: [
            'change surface tension between liquids',
            ' emulsifying, foaming',
          ],
          size: 586,
        },
      ],
    },
    {
      name: 'fillers',
      functions: [
        'give extra volume to biopolymers and composites',
        ' reduces shrinkage',
      ],
      children: [
        {
          name: 'animal',
          base: 'animal',
          origin: ['egg shells', ' hair', ' fur', ' feathers', ' bones'],
          link: 'empty',
          category: 'fillers',
          categoryFunctions: [
            'give extra volume to biopolymers and composites',
            ' reduces shrinkage',
          ],
          size: 8833,
        },
        {
          name: 'plants',
          base: 'plants',
          origin: ['stems', ' leaves', ' sawdust', ' glycerine'],
          link: 'empty',
          category: 'fillers',
          categoryFunctions: [
            'give extra volume to biopolymers and composites',
            ' reduces shrinkage',
          ],
          size: 1732,
        },
        {
          name: 'powders',
          base: 'inorganic',
          origin: ['calcium carbonate', ' activated coal'],
          link: 'https://en.wikipedia.org/wiki/Powder',
          category: 'fillers',
          categoryFunctions: [
            'give extra volume to biopolymers and composites',
            ' reduces shrinkage',
          ],
          size: 3623,
        },
      ],
    },
    {
      name: 'solvents & vehicles',
      functions: ['dissolve or extract a substance into a liquid'],
      children: [
        {
          name: 'oils',
          base: 'plants',
          origin: ['sunflower oil', ' rice oil', ' linseed oil'],
          link: 'https://en.wikipedia.org/wiki/Oil',
          category: 'solvents & vehicles',
          categoryFunctions: ['dissolve or extract a substance into a liquid'],
          size: 4116,
        },
        {
          name: 'acidic solvent',
          base: 'microbial',
          origin: ['vinegar', ' cleaning vinegar'],
          link: 'https://en.wikipedia.org/wiki/Solvent',
          category: 'solvents & vehicles',
          categoryFunctions: ['dissolve or extract a substance into a liquid'],
          size: 4116,
        },
        {
          name: 'water',
          base: 'inorganic',
          origin: ['hot/cold rainwater', ' distilled water', ' tap water'],
          link: 'https://en.wikipedia.org/wiki/Water',
          category: 'solvents & vehicles',
          categoryFunctions: ['dissolve or extract a substance into a liquid'],
          size: 4116,
        },
        {
          name: 'acidic solvent',
          base: 'chemical compounds',
          origin: ['citric acid'],
          link: 'https://en.wikipedia.org/wiki/Solvent',
          category: 'solvents & vehicles',
          categoryFunctions: ['dissolve or extract a substance into a liquid'],
          size: 4116,
        },
        {
          name: 'alcohols',
          base: 'chemical compounds',
          origin: ['ethanol', ' isopropyl alcohol', ' diethyl ether'],
          link: 'https://en.wikipedia.org/wiki/Alcohol_(chemistry)',
          category: 'solvents & vehicles',
          categoryFunctions: ['dissolve or extract a substance into a liquid'],
          size: 4116,
        },
        {
          name: 'ketones',
          base: 'chemical compounds',
          origin: ['aceton'],
          link: 'https://en.wikipedia.org/wiki/Ketosis',
          category: 'solvents & vehicles',
          categoryFunctions: ['dissolve or extract a substance into a liquid'],
          size: 4116,
        },
      ],
    },
    {
      name: 'mordants, tannins, binders, redox agents',
      functions: ['attach pigment to fibre'],
      children: [
        {
          name: 'tannins (animals)',
          base: 'animal',
          origin: ['brains', ' urine'],
          link: 'https://en.wikipedia.org/wiki/Tannin',
          category: 'mordants, tannins, binders, redox agents',
          categoryFunctions: ['attach pigment to fibre'],
          size: 1082,
        },
        {
          name: 'binder (animal)',
          base: 'animal',
          origin: ['milk'],
          link: 'empty',
          category: 'mordants, tannins, binders, redox agents',
          categoryFunctions: ['attach pigment to fibre'],
          size: 1336,
        },
        {
          name: 'reduction agent for indigo',
          base: 'animal',
          origin: ['urine'],
          link: 'empty',
          category: 'mordants, tannins, binders, redox agents',
          categoryFunctions: ['attach pigment to fibre'],
          size: 319,
        },
        {
          name: 'tannins (wood)',
          base: 'plants',
          origin: [
            'oak bark',
            ' birch bark',
            ' mango bark',
            ' cutch',
            ' terminalia chebula (myrobalan nuts)',
            ' quebracho',
          ],
          link: 'https://en.wikipedia.org/wiki/Tannin',
          category: 'mordants, tannins, binders, redox agents',
          categoryFunctions: ['attach pigment to fibre'],
          size: 10498,
        },
        {
          name: 'tannins (plants)',
          base: 'plants',
          origin: [
            'chestnuts',
            ' tea',
            ' juniper',
            ' rhubarb',
            ' staghorn sumac',
            ' pomegranate',
            ' aloe vera',
            ' acorns',
            ' oak galls',
            ' tara pulver',
            ' rhubarb leaves',
          ],
          link: 'https://en.wikipedia.org/wiki/Tannin',
          category: 'mordants, tannins, binders, redox agents',
          categoryFunctions: ['attach pigment to fibre'],
          size: 2822,
        },
        {
          name: 'binder (plants)',
          base: 'plants',
          origin: ['vegetable milk (e.g. soy milk, almond, oats)'],
          link: 'empty',
          category: 'mordants, tannins, binders, redox agents',
          categoryFunctions: ['attach pigment to fibre'],
          size: 9983,
        },
        {
          name: 'mordant',
          base: 'plants',
          origin: [
            'symplocos',
            ' club moss',
            ' rhubarb leaves (animal fibers - oxalic acid)',
          ],
          link: 'https://en.wikipedia.org/wiki/Mordant',
          category: 'mordants, tannins, binders, redox agents',
          categoryFunctions: ['attach pigment to fibre'],
          size: 2213,
        },
        {
          name: 'reduction & oxidation (redox for indigo dye)',
          base: 'plants',
          origin: ['wood ash lye'],
          link: 'empty',
          category: 'mordants, tannins, binders, redox agents',
          categoryFunctions: ['attach pigment to fibre'],
          size: 1681,
        },
        {
          name: 'reduction & oxidation (redox for indigo dye)',
          base: 'microbial',
          origin: ['sugar', ' yeast'],
          link: 'empty',
          category: 'mordants, tannins, binders, redox agents',
          categoryFunctions: ['attach pigment to fibre'],
          size: 1681,
        },
        {
          name: 'mineral mordants',
          base: 'inorganic',
          origin: ['alum (potassium aluminium sulfate)'],
          link: 'https://en.wikipedia.org/wiki/Mordant',
          category: 'mordants, tannins, binders, redox agents',
          categoryFunctions: ['attach pigment to fibre'],
          size: 1681,
        },
        {
          name: 'metal mordants',
          base: 'inorganic',
          origin: ['copper (copper sulfate)', ' iron (iron sulfate)'],
          link: 'https://en.wikipedia.org/wiki/Mordant ',
          category: 'mordants, tannins, binders, redox agents',
          categoryFunctions: ['attach pigment to fibre'],
          size: 1681,
        },
        {
          name: 'reduction & oxidation (redox for indigo dye)',
          base: 'inorganic',
          origin: [
            'sodium hydrosulphate',
            ' sodium hydroxide',
            ' ferrous sulfate',
          ],
          link: 'empty',
          category: 'mordants, tannins, binders, redox agents',
          categoryFunctions: ['attach pigment to fibre'],
          size: 1681,
        },
        {
          name: 'chemical mordants',
          base: 'chemical compounds',
          origin: [
            'alum (alum, potassium aluminium sulfate dodecahydrate, alum potash)',
            ' aluminium acetate',
          ],
          link: 'https://en.wikipedia.org/wiki/Mordant',
          category: 'mordants, tannins, binders, redox agents',
          categoryFunctions: ['attach pigment to fibre'],
          size: 1681,
        },
      ],
    },
    {
      name: 'miscellaneous',
      functions: ['pH buffer (stabilizes pH)', 'crosslinkers', 'desinfectants'],
      children: [
        {
          name: 'pH buffers',
          base: 'animal',
          origin: ['sea shells', ' mussel shells', ' egg shells'],
          link: 'https://en.wikipedia.org/wiki/Buffer_solution',
          category: 'miscellaneous',
          categoryFunctions: [
            'pH buffer (stabilizes pH)',
            'crosslinkers',
            'desinfectants',
          ],
          size: 1616,
        },
        {
          name: 'crosslinker',
          base: 'plants',
          origin: [
            'lemon juice (for starches)',
            ' orange juice (for alginate)',
          ],
          link: 'https://en.wikipedia.org/wiki/Cross-link',
          category: 'miscellaneous',
          categoryFunctions: [
            'pH buffer (stabilizes pH)',
            'crosslinkers',
            'desinfectants',
          ],
          size: 1027,
        },
        {
          name: 'crosslinker',
          base: 'microbial',
          origin: ['vinegar (for starches)'],
          link: 'https://en.wikipedia.org/wiki/Cross-link',
          category: 'miscellaneous',
          categoryFunctions: [
            'pH buffer (stabilizes pH)',
            'crosslinkers',
            'desinfectants',
          ],
          size: 3891,
        },
        {
          name: 'disinfectant',
          base: 'microbial',
          origin: ['denatured alcohol 70%'],
          link: 'https://en.wikipedia.org/wiki/Disinfectant',
          category: 'miscellaneous',
          categoryFunctions: [
            'pH buffer (stabilizes pH)',
            'crosslinkers',
            'desinfectants',
          ],
          size: 891,
        },
        {
          name: 'pH buffers',
          base: 'inorganic',
          origin: ['chalk', ' gypsum'],
          link: 'https://en.wikipedia.org/wiki/Buffer_solution',
          category: 'miscellaneous',
          categoryFunctions: [
            'pH buffer (stabilizes pH)',
            'crosslinkers',
            'desinfectants',
          ],
          size: 2893,
        },
        {
          name: 'crosslinker',
          base: 'chemical compounds',
          origin: [
            'calcium chloride (for alginate)',
            ' citric acid (for starches)',
          ],
          link: 'https://en.wikipedia.org/wiki/Cross-link',
          category: 'miscellaneous',
          categoryFunctions: [
            'pH buffer (stabilizes pH)',
            'crosslinkers',
            'desinfectants',
          ],
          size: 5103,
        },
        {
          name: 'pH buffers',
          base: 'chemical compounds',
          origin: ['calcium carbonate', ' calcium hydroxide'],
          link: 'https://en.wikipedia.org/wiki/Buffer_solution',
          category: 'miscellaneous',
          categoryFunctions: [
            'pH buffer (stabilizes pH)',
            'crosslinkers',
            'desinfectants',
          ],
          size: 3677,
        },
        {
          name: 'disinfectant',
          base: 'chemical compounds',
          origin: ['hypocholorite bleach (10% solution)'],
          link: 'https://en.wikipedia.org/wiki/Disinfectant',
          category: 'miscellaneous',
          categoryFunctions: [
            'pH buffer (stabilizes pH)',
            'crosslinkers',
            'desinfectants',
          ],
          size: 781,
        },
      ],
    },
    {
      name: 'growth media',
      functions: ['various functions in microbiological lab work'],
      children: [
        {
          name: 'solidifying agent',
          base: 'animal',
          origin: ['gelatine'],
          link: 'empty',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 2105,
        },
        {
          name: 'protein',
          base: 'animal',
          origin: ['peptone', ' tryptone beef broth', ' meat extract'],
          link: 'https://en.wikipedia.org/wiki/Protein',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 1316,
        },
        {
          name: 'carbon (sugars)',
          base: 'animal',
          origin: ['honey', ' peptone'],
          link: 'https://en.wikipedia.org/wiki/Carbon',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 3151,
        },
        {
          name: 'pH buffer',
          base: 'animal',
          origin: ['peptone'],
          link: 'https://en.wikipedia.org/wiki/Buffer_solution',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 3770,
        },
        {
          name: 'nitrogen',
          base: 'animal',
          origin: ['peptone'],
          link: 'https://en.wikipedia.org/wiki/Nitrogen',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 2435,
        },
        {
          name: 'sulfur',
          base: 'animal',
          origin: ['peptone'],
          link: 'https://en.wikipedia.org/wiki/Sulfur',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 4839,
        },
        {
          name: 'enzyme exciters (e.g. vitamin B)',
          base: 'animal',
          origin: ['beef extract', ' meat extract'],
          link: 'empty',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 1756,
        },
        {
          name: 'carbon (sugars)',
          base: 'plants',
          origin: [
            'malt extract',
            ' glucose',
            ' dextrose',
            ' corn syrup',
            ' sugar',
            ' potato',
            ' vegetable peptone',
            ' starches',
            ' dextrose',
            ' maltose',
            ' glycerine',
          ],
          link: 'https://en.wikipedia.org/wiki/Carbon',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 4268,
        },
        {
          name: 'protein',
          base: 'plants',
          origin: ['vegetable peptone'],
          link: 'https://en.wikipedia.org/wiki/Protein',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 1821,
        },
        {
          name: 'pH buffer',
          base: 'plants',
          origin: ['vegetable peptone'],
          link: 'https://en.wikipedia.org/wiki/Buffer_solution',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 1821,
        },
        {
          name: 'nitrogen',
          base: 'plants',
          origin: ['vegetable peptone'],
          link: 'https://en.wikipedia.org/wiki/Nitrogen',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 1821,
        },
        {
          name: 'sulfur',
          base: 'plants',
          origin: ['vegetable peptone'],
          link: 'https://en.wikipedia.org/wiki/Sulfur',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 1821,
        },
        {
          name: 'enzyme exciters (e.g. vitamin B)',
          base: 'microbial',
          origin: ['yeast'],
          link: 'empty',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 1821,
        },
        {
          name: 'solidifying agent',
          base: 'microbial',
          origin: ['agar'],
          link: 'empty',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 1821,
        },
        {
          name: 'isotonic agent',
          base: 'inorganic',
          origin: [
            'salt',
            ' glycerol',
            ' mannitol',
            ' gypsum',
            ' calsium carbonate',
          ],
          link: 'empty',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 1821,
        },
        {
          name: 'pH modifier',
          base: 'chemical compounds',
          origin: [
            'citric acid',
            ' tartaric acid (acidic)',
            ' sodium hydroxide (alkaline)',
          ],
          link: 'empty',
          category: 'growth media',
          categoryFunctions: ['various functions in microbiological lab work'],
          size: 1821,
        },
      ],
    },
  ],
};
